// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1600946926);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1600946446);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1600946686);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1600946806);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1600946566);
user_pref("browser.cache.disk.amount_written", 671);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "IN");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 22 Sep 2020 11:07:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1600946926);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"00ee3666-4114-4c0c-8973-fd1a25e03acb\",\"default-theme@mozilla.org\":\"6e906314-10f4-4def-bdf3-9c229fbafa64\",\"google@search.mozilla.org\":\"70b245c9-a0d2-4688-8df7-884d47075ab2\",\"amazondotcom@search.mozilla.org\":\"1c0dd788-13f8-4750-9dfb-2db4ca26055c\",\"bing@search.mozilla.org\":\"49ab337c-14bb-4887-b889-64b19dc1dfff\",\"ddg@search.mozilla.org\":\"12d7822a-789a-4aab-bf75-d612c3544b55\",\"twitter@search.mozilla.org\":\"9bf97d7c-9bc0-4023-ae46-8c534d9ace48\",\"wikipedia@search.mozilla.org\":\"2af63926-0fa3-4415-ad98-edfa4916035c\"}");
user_pref("idle.lastDailyNotification", 1600947550);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "9486ff34-be32-45f4-bce8-8d66e49a7fe");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1600947550);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "d5246f43-aff4-43ef-b0af-89619afeadb7");
user_pref("services.blocklist.pinning.checked", 1600946806);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1600905679357\"");
user_pref("services.settings.last_update_seconds", 1600946806);
user_pref("services.settings.main.hijack-blocklists.last_check", 1600946806);
user_pref("services.settings.main.language-dictionaries.last_check", 1600946806);
user_pref("services.settings.main.sites-classification.last_check", 1600946806);
user_pref("services.settings.security.onecrl.checked", 1600946806);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1600947550);
user_pref("toolkit.telemetry.cachedClientID", "8539fe00-60a1-46a5-8096-762af4c03460");
user_pref("toolkit.telemetry.prompted", 2);
